version: "3"
services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: DockerfileWeb
        ports:
            - "3000:3000"
        volumes:
            - .:/opt/node_app/app:delegated
            - ./package.json:/opt/node_app/package.json
            - /opt/node_app/app/node_modules/
        environment: 
            - PORT=3000
    server:
        image: vimagick/json-server
        command: -H 0.0.0.0 -p 4000 -w db.json
        ports:
          - "4000:4000"
        volumes:
          - ./data:/data
        restart: always